root/Source/ServiceOrder.WebSite/Controllers/RegionController.cs
using System.Web.Mvc;
using ServiceOrder.Logic.Services;
using ServiceOrder.ViewModel.ViewModels.Implementation.RegionViewModels;

namespace ServiceOrder.WebSite.Controllers
{
    [Authorize(Roles = "admin")]
    public class RegionController : Controller
    {
        private IRegionService _regionService;

        public RegionController(IRegionService regionService)
        {
            _regionService = regionService;
        }

        // GET: Region
        public ActionResult Index()
        {
            return View(_regionService.GetAll());
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(RegionEntityViewModel model)
        {
            if (ModelState.IsValid)
            {
                _regionService.Add(model);
            }          
            return View("Index",_regionService.GetAll()); 
        }

        public ActionResult Edit(int? id)
        {
            return View(_regionService.Get(id));
        }

        [HttpPost]
        public ActionResult Edit(RegionEntityViewModel model)
        {
            if (ModelState.IsValid)
            {
                _regionService.Update(model);
            }
            return View("Index", _regionService.GetAll());
        }

        public ActionResult Delete(int? id)
        {
            _regionService.Delete(id);
            return View("Index", _regionService.GetAll());
        }

    }
}

root/Source/ServiceOrder.WebSite/Views/Region/Create.cshtml
@model ServiceOrder.ViewModel.ViewModels.Implementation.RegionViewModels.RegionEntityViewModel

@{
    ViewBag.Title = "Create Region";
}

<h2>Create Region</h2>


<div class="row">
    @using (Html.BeginForm("Create", "Region", FormMethod.Post, new { @class = "category-create-form col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 col-xs-10"}))
    {
        @Html.AntiForgeryToken()

        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Region Title" } })
        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <input type="submit" value="Create" class="btn btn-default" />

    }
</div>

<div>
    @Html.ActionLink("Back to List", "Index",null,new {@class="btn btn-default"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

root/Source/ServiceOrder.WebSite/Views/Region/Edit.cshtml
@model ServiceOrder.ViewModel.ViewModels.Implementation.RegionViewModels.RegionEntityViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit Region</h2>


<div class="row">
    @using (Html.BeginForm("Edit", "Region", FormMethod.Post, new { @class = "category-create-form col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 col-xs-12" }))
    {
        @Html.AntiForgeryToken()

        <div class="container">
            @Html.HiddenFor(model => model.Id)

            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label edit-title" })

            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control edit-input-with-label" } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })


            <input type="submit" value="Save" class="btn btn-default " />
        </div>
    }
</div>

<div>
    @Html.ActionLink("Back to List", "Index",null,new {@class="btn btn-default"})
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

root/Source/ServiceOrder.WebSite/Views/Region/Index.cshtml
@model IEnumerable<ServiceOrder.ViewModel.ViewModels.Implementation.RegionViewModels.RegionEntityViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Regions</h2>
<br />
<p>
    @Html.ActionLink("Create New", "Create",null,new {@class="btn btn-default"})
</p>
<br />
<table class="table table-striped ">
    <tr class="row">
        <th class="col-md-10 col-lg-10 col-xs-8 col-sm-8">
            @Html.DisplayNameFor(model => model.Title)
        </th>
        <th class="col-md-10 col-lg-10 col-xs-8 col-sm-8"></th>
    </tr>

@foreach (var item in Model) {
    <tr class="row">
        <td class="col-md-10 col-lg-10 col-xs-8 col-sm-8">
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td class="col-md-10 col-lg-10 col-xs-8 col-sm-8">
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>