root/Source/ServiceOrder.WebSite/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ServiceOrder.Logic.Services;
using ServiceOrder.ViewModel.ViewModels.Implementation;
using ServiceOrder.ViewModel.ViewModels.Implementation.PhotoViewModels;

namespace ServiceOrder.WebSite.Controllers
{
    public class AlbumController : Controller
    {
        private IAlbumService _albumService;

        public AlbumController(IAlbumService albumService)
        {
            _albumService = albumService;
        }

        [Authorize(Roles = "service provider")]
        public ActionResult Add(int albumId)
        {
            var album = _albumService.Get(albumId);
            if (album == null)
            {
                return View("MessageView", new ResultMessageViewModel() {Message = "There's no such album"});
            }
            return User.Identity.GetUserId() != album.ServiceProviderId
                ? View("MessageView", new ResultMessageViewModel() {Message = "You don't has access to this album"})
                : View(album);
        }

        [HttpPost]
        [Authorize(Roles = "service provider")]
        public JsonResult Upload(int albumId)
        {
            var files = new List<AbstractDataUploadResult>();

            _albumService.UploadAndShowResults(HttpContext, files, albumId);

            bool isEmpty = !files.Any();
            return isEmpty ? Json("Error") : Json(new {files = files});
        }

        [Authorize(Roles = "service provider")]
        public ActionResult Edit(int albumId)
        {
            var album = _albumService.Get(albumId);
            if (album == null)
            {
                return View("MessageView", new ResultMessageViewModel() {Message = "There's no such album"});
            }
            return User.Identity.GetUserId() != album.ServiceProviderId
                ? View("MessageView", new ResultMessageViewModel() {Message = "You don't has access to this album"})
                : View(album);
        }

        public JsonResult GetFileList(int albumId)
        {
            try
            {  
                var list = _albumService.GetPhotosList(albumId);
                return Json(new {files = list}, JsonRequestBehavior.AllowGet);
            }
            catch (Exception exception)
            {
                Response.StatusCode = (int) HttpStatusCode.BadRequest;
                Response.StatusDescription = exception.Message;
                return Json(new {success = false}, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [Authorize(Roles = "service provider")]
        public ActionResult ChangeAlbumTitle(int albumId,string albumTitle)
        {
            var result = _albumService.ChangeAlbumTitle(User.Identity.GetUserId(), albumId, albumTitle);
            if (result.Equals(String.Empty))
            {
                return new HttpStatusCodeResult(200, "OK");
            }
            return new HttpStatusCodeResult(400, result);
        }
    }
}

root/Source/ServiceOrder.WebSite/Controllers/PhotoController.cs
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ServiceOrder.Logic.Services;

namespace ServiceOrder.WebSite.Controllers
{
    public class PhotoController : Controller
    {
        private IPhotoService _photoService;
        public PhotoController(IPhotoService photoService)
        {
            _photoService = photoService;
        }
        public FileContentResult Get(int? photoId)
        {
            var photo = _photoService.GetPhoto(photoId);
            if (photo == null) return null;
            return File(photo.PhotoImage,photo.ContentType,photo.FileName);
        }

        [Authorize(Roles = "service provider")]
        [HttpGet]
        public JsonResult Delete(int? photoId)
        {
            _photoService.Delete(photoId,User.Identity.GetUserId());
            return Json("OK", JsonRequestBehavior.AllowGet);
        }
    }
}

root/Source/ServiceOrder.WebSite/Controllers/ServiceProvidersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using PagedList;
using ServiceOrder.Logic.Services;
using ServiceOrder.ViewModel.ViewModels.Implementation;
using ServiceOrder.ViewModel.ViewModels.Implementation.AlbumViewModels;
using ServiceOrder.ViewModel.ViewModels.Implementation.RegionViewModels;
using ServiceOrder.ViewModel.ViewModels.Implementation.ServiceCategoryViewModels;
using ServiceOrder.ViewModel.ViewModels.Implementation.ServiceProvidersViewModels;
using ServiceOrder.ViewModel.ViewModels.Implementation.ServiceTypeViewModels;

namespace ServiceOrder.WebSite.Controllers
{
    public class ServiceProvidersController : Controller
    {
        private IServiceProviderService _provider;
        private IRegionService _regionService;
        private ICategoryService _categoryService;
        private IServiceTypeService _serviceTypeService;
        private IAlbumService _albumService;
        

        public ServiceProvidersController(IServiceProviderService provider, IRegionService regionService,
            ICategoryService categoryService,IServiceTypeService serviceTypeService, IAlbumService albumService)
        {
            _provider = provider;
            _regionService = regionService;
            _categoryService = categoryService;
            _serviceTypeService = serviceTypeService;
            _albumService = albumService;
        }

        // GET: ServiceProviders
        [Authorize(Roles = "client")]
        public ActionResult Index()
        {
            var model = new ServiceProviderPaginationFiltrationList();
            var pageSize = 5;
            model.Page = 1;
            model.ProviderList = _provider.GetAllWithServiceAndRegion().ToPagedList(model.Page.Value, pageSize);
            
            return View(model);
        }

        [Authorize(Roles = "client")]
        public ActionResult Filter(ServiceProviderPaginationFiltrationList model)
        {
            var pageSize = 5;
            var pageNumber = (model.Page ?? 1);
            model.ProviderList =
                _provider.FilterGetProviders(model.RegionId, model.CategoryId, model.ServiceId)
                    .ToPagedList(pageNumber, pageSize);
            return View("Index",model);
        }

        [Authorize(Roles = "service provider")]
        public ActionResult Manage(ServiceProviderViewModel model)
        {
            if (ModelState.IsValid)
            {
                var provider = _provider.Get(User.Identity.GetUserId());
                return View(provider);
            }
            else
            {
                return View(model);
            }
            
        }

        [HttpPost]
        [Authorize(Roles = "service provider")]
        public ActionResult EditDescription(string description)
        {
            var result = _provider.ChangeDescription(User.Identity.GetUserId(), description);
            if (result.Equals(String.Empty))
            {
                return new HttpStatusCodeResult(200, "OK");
            }
            return new HttpStatusCodeResult(400, result);
        }

        [HttpGet]
        [Authorize(Roles = "service provider")]
        public ActionResult AddRegion()
        {
            var regionViewModel = new ServiceProviderRegionsViewModel();
            var allRegions = _regionService.GetAll().ToList();
            var provider = _provider.Get(User.Identity.GetUserId());

            regionViewModel.providerRegions = provider.Regions;
            regionViewModel.allRegions = new List<RegionEntityViewModel>();
            foreach (var item in allRegions)
            {
                if (!regionViewModel.providerRegions.Contains(item))
                {
                    regionViewModel.allRegions.Add(item);
                }
            }
            return View(regionViewModel);
        }

        [HttpPost]
        [Authorize(Roles = "service provider")]
        public ActionResult AddRegion(string s)
        {
            try
            {
                List<RegionEntityViewModel> regions = JsonConvert.DeserializeObject<List<RegionEntityViewModel>>(s);
                if (regions == null)
                {
                    return new HttpStatusCodeResult(400, "Wrong regions dataS");
                }
                var provider = _provider.Get(User.Identity.GetUserId());
                provider.Regions = regions;
                _provider.Update(provider);

            }
            catch (Exception exception)
            {
                return new HttpStatusCodeResult(400,  exception.Message);
            }
            return new HttpStatusCodeResult(200, "OK"); ;
        }


        [Authorize(Roles = "service provider")]
        public ActionResult DeleteRegion(int regionId)
        {
            var provider = _provider.Get(User.Identity.GetUserId());
            try
            {
                var region = _regionService.Get(regionId);
                if (region == null)
                {
                    throw new Exception("Wrond region parametr");
                }
                _provider.DeleteRegion(region,provider);
            }
            catch (Exception exception)
            {
                return View("MessageView", new ResultMessageViewModel { Message = exception.Message });
            }
            return RedirectToAction("Manage");
        }

        [HttpGet]
        [Authorize(Roles = "service provider")]
        public ActionResult AddService()
        {
            var model = new ServiceProviderCategoryViewModel {Categories = _categoryService.GetAll().ToList()};
            return View(model);
        }

        [HttpGet]
        [Authorize(Roles = "client")]
        public ActionResult GetRegions()
        {
            try
            {
                var regions = _regionService.GetAll();
                return Json(new {regions = JsonConvert.SerializeObject(regions)}, JsonRequestBehavior.AllowGet);
            }
            catch (Exception exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest,exception.Message);
            }

        }

        [HttpGet]
        public ActionResult GetCategories()
        {
            try
            {
                var categories = _categoryService.GetAll();
                return Json(new { categories = JsonConvert.SerializeObject(categories) }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, exception.Message);
            }
        }

        [HttpGet]
        public ActionResult GetCategoryServicesAll(int Id)
        {
            try
            {
                var servicesAll = _serviceTypeService.FindServicesInCategory(Id);
                var serviceTypeViewModels = servicesAll as IList<ServiceTypeViewModel> ?? servicesAll.ToList();
                var allServices = serviceTypeViewModels.Select(item => new ServiceShortViewModel { Id = item.Id, Title = item.Title }).ToList();
                return Json(new { services = JsonConvert.SerializeObject(allServices) }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception exception)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, exception.Message);
            }
        }

        [HttpGet]
        public ActionResult GetCategoryServices(int Id)
        {
            var servicesAll = _serviceTypeService.FindServicesInCategory(Id);
            var providerServices = _provider.Get(User.Identity.GetUserId()).Services.Where(src => src.Category.Id == Id).ToList();

            var providerServicesIndex = new List<int>();
            var serviceTypeViewModels = servicesAll as IList<ServiceTypeViewModel> ?? servicesAll.ToList();
            var allServices = serviceTypeViewModels.Select(item => new ServiceShortViewModel {Id = item.Id, Title = item.Title}).ToList();

            for (var i = 0; i < allServices.Count; i++)
            {
                var item = allServices[i];
                if (providerServices.Count(providerItem => providerItem.Id == item.Id) != 0x0)
                {
                    providerServicesIndex.Add(i);
                }
            }
            return Json(new {dataAll = JsonConvert.SerializeObject(allServices), chooseData = JsonConvert.SerializeObject(providerServicesIndex) }, JsonRequestBehavior.AllowGet) ;
        }

        [HttpPost]
        public ActionResult AddServices(string services,string category)
        {
            try
            {
                List<ServiceTypeViewModel> servicesList = JsonConvert.DeserializeObject<List<ServiceTypeViewModel>>(services);
                ServiceCategoryEntityViewModel categoryEntity =
                    JsonConvert.DeserializeObject<ServiceCategoryEntityViewModel>(category);
                if (services == null)
                {
                    return new HttpStatusCodeResult(400, "Wrong services data");
                }
                var provider = _provider.Get(User.Identity.GetUserId());
                _provider.UpdateServices(servicesList,provider,categoryEntity);

            }
            catch (Exception exception)
            {
                return new HttpStatusCodeResult(400, exception.Message);
            }
            return  new HttpStatusCodeResult(200, "OK");
        }

        [Authorize(Roles = "service provider")]
        public ActionResult DeleteService(int serviceId)
        {
            var provider = _provider.Get(User.Identity.GetUserId());
            try
            {
                var service = _serviceTypeService.Get(serviceId);
                if (service == null)
                {
                    throw new Exception("Wrond service parametr");
                }

root/Source/ServiceOrder.WebSite/Views/Album/Add.cshtml
@model ServiceOrder.ViewModel.ViewModels.Implementation.AlbumViewModels.AlbumViewModel

@{
    ViewBag.Title = "Index";
}

@Styles.Render("~/Content/jQuery-File-Upload")
@Styles.Render("~/Content/Blueimp-Gallery")

<script>
    var $form = null;
    $(function () {

        $form = $('#fileupload').fileupload({
            dataType: 'json'
        });

    });
    $('#fileupload').addClass('fileupload-processing');

</script>
@Html.Partial("_Photo")


<div class="row">
    @Html.ActionLink("Back to Management", "ManageAlbum", "ServiceProviders", new { albumId = @Model.Id }, new { @class = "btn btn-default backButtonMargin" })
</div>

@Scripts.Render("~/bundles/jQuery-File-Upload")

root/Source/ServiceOrder.WebSite/Views/Album/Edit.cshtml
@model ServiceOrder.ViewModel.ViewModels.Implementation.AlbumViewModels.AlbumViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<span id="notification" style="display: none;"></span>

@Styles.Render("~/Content/jQuery-File-Upload")
@Styles.Render("~/Content/Blueimp-Gallery")

<script>
    var $form = null;
    $(function() {

        $form = $('#fileupload').fileupload({
            dataType: 'json'
        });

    });
    $('#fileupload').addClass('fileupload-processing');


    
</script>

@Html.Partial("_Photo")

<div class="row">
    @Html.ActionLink("Back to Management", "ManageAlbum", "ServiceProviders", new {albumId = @Model.Id}, new { @class = "btn btn-default backButtonMargin" })
</div>

@Scripts.Render("~/bundles/jQuery-File-Upload")

<script id="errorTemplate" type="text/x-kendo-template">
    <div class="error-notification">
        <img src="http://demos.telerik.com/kendo-ui/content/web/notification/error-icon.png" />
        <h3>#= title #</h3>
        <p>#= message #</p>
    </div>
</script>

<script id="successTemplate" type="text/x-kendo-template">
    <div class="success-notification">
        <img src="http://demos.telerik.com/kendo-ui/content/web/notification/success-icon.png" />
        <h3>#= message #</h3>
    </div>
</script>

<script>
    var notification = $("#notification").kendoNotification({
        position: {
            pinned: true,
            top: 50,
            right: 30
        },
        autoHideAfter: 5000,
        stacking: "down",
        templates: [{
            type: "error",
            template: $("#errorTemplate").html()
        }, {
            type: "success",
            template: $("#successTemplate").html()
        }]
    }).data("kendoNotification");

    $.ajax({
            type: 'GET',
            contentType: "application/json; charset=utf-8",
            url: '/Album/GetFileList',
            data: { albumId:@Model.Id},
            success: function(data) {
                $('#fileupload').fileupload('option', 'done').call($('#fileupload'), $.Event('done'), { result: { files: data.files } })
                $('#fileupload').removeClass('fileupload-processing');
            },
            error: function (error) {
                notification.show({
                    title: "Error",
                    message: error.statusText
                }, "error");
            }

        }
    );
</script>

root/Source/ServiceOrder.WebSite/Views/Album/_Photo.cshtml
@model ServiceOrder.ViewModel.ViewModels.Implementation.AlbumViewModels.AlbumViewModel

<form id="fileupload" method="POST" enctype="multipart/form-data" data-url="@Url.Action("Upload","Album")">
    <div class="row fileupload-buttonbar">
        <div class="col-lg-7">
            <input type="hidden" name="albumId" value="@Model.Id">
            <!-- The fileinput-button span is used to style the file input field as button -->
            <span class="btn btn-success fileinput-button">
                <i class="glyphicon glyphicon-plus"></i>
                <span>Add files...</span>
                <input type="file" name="files[]" multiple accept="image/*">
            </span>
            <button type="submit" class="btn btn-primary start">
                <i class="glyphicon glyphicon-upload"></i>
                <span>Start upload</span>
            </button>
            <button type="reset" class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel upload</span>
            </button>
            <button type="button" class="btn btn-danger delete">
                <i class="glyphicon glyphicon-trash"></i>
                <span>Delete</span>
            </button>
            <input type="checkbox" class="toggle">
            <!-- The global file processing state -->
            <span class="fileupload-process"></span>
        </div>
        <!-- The global progress state -->
        <div class="col-lg-5 fileupload-progress fade">
            <!-- The global progress bar -->
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-success" style="width:0%;"></div>
            </div>
            <!-- The extended global progress state -->
            <div class="progress-extended">&nbsp;</div>
        </div>
    </div>
    <!-- The global progress state -->
    <div class="col-lg-5 fileupload-progress fade">
        <!-- The global progress bar -->
        <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100">
            <div class="progress-bar progress-bar-success" style="width:0%;"></div>
        </div>
        <!-- The extended global progress state -->
        <div class="progress-extended">&nbsp;</div>
    </div>

    <!-- The table listing the files available for upload/download -->
    <table role="presentation" class="table table-striped"><tbody class="files"></tbody></table>
</form>
<br>
<!-- The blueimp Gallery widget -->
<div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
    <div class="slides"></div>
    <h3 class="title"></h3>
    <a class="prev">‹</a>
    <a class="next">›</a>
    <a class="close">×</a>
    <a class="play-pause"></a>
    <ol class="indicator"></ol>
</div>

<script>
    $(document).ready(function () {
        
        $('#fileupload').fileupload({
            maxFileSize: 10485760
        });
       });
</script>
<script id="template-upload" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
   
    <tr class="template-upload fade">
        <td>
            <span class="preview"></span>
        </td>
        <td>
            <p class="name">{%=file.name%}</p>
            <strong class="error text-danger"></strong>
        </td>
        <td>
            <p class="size">Processing...</p>
            <div class="progress progress-striped active" role="progressbar" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="progress-bar progress-bar-success" style="width:0%;"></div></div>
        </td>
        <td>
            {% if (!i && !o.options.autoUpload) { %}
            <button class="btn btn-primary start" disabled>
                <i class="glyphicon glyphicon-upload"></i>
                <span>Start</span>
            </button>
            {% } %}
            {% if (!i) { %}
            <button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">
    {% for (var i=0, file; file=o.files[i]; i++) { %}
    <tr class="template-download fade">
        <td>
            <span class="preview">
                {% if (file.thumbnailUrl) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" data-gallery><img src="{%=file.thumbnailUrl%}" class="imageThumbnailSize"></a>
                {% } %}
            </span>
        </td>
        <td>
            <p class="name">
                {% if (file.url) { %}
                <a href="{%=file.url%}" title="{%=file.name%}" download="{%=file.name%}" {%=file.thumbnailUrl?'data-gallery':''%}>{%=file.name%}</a>
                {% } else { %}
                <span>{%=file.name%}</span>
                {% } %}
            </p>
            {% if (file.error) { %}
            <div><span class="label label-danger">Error</span> {%=file.error%}</div>
            {% } %}
        </td>
        <td>
            <span class="size">{%=o.formatFileSize(file.size)%}</span>
        </td>
        <td>
            {% if (file.deleteUrl) { %}
            <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}" {% if (file.deletewithcredentials) { %} data-xhr-fields='{"withCredentials":true}' {% } %}>
                <i class="glyphicon glyphicon-trash"></i>
                <span>Delete</span>
            </button>
            <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
            <button class="btn btn-warning cancel">
                <i class="glyphicon glyphicon-ban-circle"></i>
                <span>Cancel</span>
            </button>
            {% } %}
        </td>
    </tr>
    {% } %}
</script>