root/Source/ServiceOrder.WebSite/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using ServiceOrder.Logic.Services;
using ServiceOrder.ViewModel.ViewModels.Implementation.ServiceCategoryViewModels;

namespace ServiceOrder.WebSite.Controllers
{
    [Authorize(Roles = "admin")]
    public class CategoryController : Controller
    {
        private ICategoryService _categoryService;

        public CategoryController(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ActionResult Index()
        {
            IEnumerable<ServiceCategoryEntityViewModel> categories = _categoryService.GetAll();
            return View(categories);
        }

        public ActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateCategory(ServiceCategoryEntityViewModel categoryEntity)
        {
            try
            {
                _categoryService.Add(categoryEntity);
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Can't add category.");
                return View(categoryEntity);
            }

            return RedirectToAction("Index");
        }

        public ActionResult DeleteCategory(int? id)
        {
            _categoryService.Delete(id);
            return RedirectToAction("Index");
        }

        public ActionResult EditCategory(int? id)
        {
            return View(_categoryService.Get(id));
        }

        [HttpPost]
        public ActionResult EditCategory(ServiceCategoryEntityViewModel categoryEntity)
        {
            _categoryService.Update(categoryEntity);
            return RedirectToAction("Index");
        }

        public ActionResult DetailCategory(int? id)
        {
            return View(_categoryService.Get(id));
        }

        protected override void Dispose(bool disposing)
        {
            _categoryService.Dispose();
            base.Dispose(disposing);
        }
    }
}

root/Source/ServiceOrder.WebSite/Controllers/OrderController.cs
using System;
using System.Linq;
using System.Net;
using System.Text;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using PagedList;
using ServiceOrder.Logic.Services;
using ServiceOrder.ViewModel.ViewModels.Implementation;
using ServiceOrder.ViewModel.ViewModels.Implementation.Order;
using ServiceOrder.ViewModel.ViewModels.Implementation.ServiceProvidersViewModels;

namespace ServiceOrder.WebSite.Controllers
{
    public class OrderController : Controller
    {
        private IOrderService _orderService;
        private IServiceProviderService _serviceProviderService;
        private ICategoryService _categoryService;

        public OrderController(IOrderService orderService, IServiceProviderService serviceProviderService,
            ICategoryService categoryService)
        {
            _orderService = orderService;
            _serviceProviderService = serviceProviderService;
            _categoryService = categoryService;
        }

        // GET: Order
        [Authorize(Roles = "client")]
        public ActionResult Index(string providerId)
        {
            var provider = new ServiceProviderViewModel();
            try
            {
                provider = _serviceProviderService.Get(providerId);
            }
            catch (Exception exception)
            {
                return View("MessageView", new ResultMessageViewModel {Message = exception.Message});
            }

            if (provider == null)
            {
                return View("MessageView", new ResultMessageViewModel {Message = "There is not such provider"});
            }

            var model = new OrderViewModel();
            foreach (var region in provider.Regions)
            {
                model.Regions.Add(region);
            }

            foreach (var service in provider.Services)
            {
                if (model.Categories.Count(category => category.Id == service.Category.Id) == 0x0)
                {
                    model.Categories.Add(service.Category);
                }
            }

            model.Regions.Sort((firstRegion, secondRegion) => firstRegion.Id.CompareTo(secondRegion.Id));
            model.Categories.Sort((firstCategory, secondCategory) => firstCategory.Id.CompareTo(secondCategory.Id));
            model.ServiceProviderId = provider.Id;
            model.ProviderName = provider.Name;

            return View(model);
        }


        [HttpGet]
        [Authorize(Roles = "client")]
        public ActionResult GetProviderServicesByCategory(int categoryId, string providerId)
        {
            ServiceProviderViewModel provider;
            try
            {
                provider = _serviceProviderService.Get(providerId);
                if (_categoryService.Get(categoryId) == null)
                {
                    throw new Exception("Wrong category");
                }

            }
            catch (Exception exception)
            {

                return new HttpStatusCodeResult(400, exception.Message);
            }

            if (provider.Services.Count(service => service.Category.Id == categoryId) == 0x0)
            {
                return new HttpStatusCodeResult(400, "This provider doesn't has services in this category");
            }
            var shortServices =
                provider.Services.Where(item => item.Category.Id == categoryId)
                    .Select(item => new ServiceShortViewModel {Id = item.Id, Title = item.Title});
            return Json(new {services = JsonConvert.SerializeObject(shortServices)}, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        [Authorize(Roles = "client")]
        public ActionResult MakeOrder(OrderViewModel order)
        {
            if (order == null)
            {
                return new HttpStatusCodeResult(400, "Null order");
            }
            try
            {
                order.ClientId = User.Identity.GetUserId();
                _orderService.Add(order);
            }
            catch (AggregateException aggregateException)
            {
                var builder = new StringBuilder();
                foreach (var exception in aggregateException.InnerExceptions)
                {
                    builder.Append(exception.Message);
                }
                return new HttpStatusCodeResult(400, builder.ToString());
            }
            catch (Exception exception)
            {
                return new HttpStatusCodeResult(400, exception.Message);
            }
            return new HttpStatusCodeResult(200, "");
        }

        [HttpGet]
        [Authorize(Roles = "client")]
        public ActionResult ClientOrders(int? page,string sortOrder)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSort = sortOrder == "Date" ? "Date_desc" : "Date";
            ViewBag.RegionSort = sortOrder == "Region" ? "Region_desc" : "Region";
            ViewBag.ServiceTypeSort = sortOrder == "ServiceType" ? "ServiceType_desc" : "ServiceType";
            ViewBag.ProviderNameSort = sortOrder == "ProviderName" ? "ProviderName_desc" : "ProviderName";

            var clientOrders = _orderService.FindClientOrders(User.Identity.GetUserId());
            switch (sortOrder)
            {
                case "Date":
                    clientOrders = clientOrders.OrderBy(key => key.Date);
                    break;
                case "Date_desc":
                    clientOrders = clientOrders.OrderByDescending(key => key.Date);
                    break;
                case "Region":
                    clientOrders = clientOrders.OrderBy(key => key.Region.Title);
                    break;
                case "Region_desc":
                    clientOrders = clientOrders.OrderByDescending(key => key.Region.Title);
                    break;
                case "ServiceType":
                    clientOrders = clientOrders.OrderBy(key => key.ServiceType.Title);
                    break;
                case "ServiceType_desc":
                    clientOrders = clientOrders.OrderByDescending(key => key.ServiceType.Title);
                    break;
                case "ProviderName":
                    clientOrders = clientOrders.OrderBy(key => key.ProviderName);
                    break;
                case "ProviderName_desc":
                    clientOrders = clientOrders.OrderByDescending(key => key.ProviderName);
                    break;
            }
            var pageSize = 5;
            var pageNumber = (page ?? 1);
            return View(clientOrders.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [Authorize(Roles = "service provider")]
        public ActionResult ProviderOrders(int? page, string sortOrder)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSort = sortOrder == "Date" ? "Date_desc" : "Date";
            ViewBag.RegionSort = sortOrder == "Region" ? "Region_desc" : "Region";
            ViewBag.ServiceTypeSort = sortOrder == "ServiceType" ? "ServiceType_desc" : "ServiceType";
            ViewBag.ClientNameSort = sortOrder == "ClientName" ? "ClientName_desc" : "ClientName";

            var providerOrders = _orderService.FindProviderOrders(User.Identity.GetUserId());
            switch (sortOrder)
            {
                case "Date":
                    providerOrders = providerOrders.OrderBy(key => key.Date);
                    break;
                case "Date_desc":
                    providerOrders = providerOrders.OrderByDescending(key => key.Date);
                    break;
                case "Region":
                    providerOrders = providerOrders.OrderBy(key => key.Region.Title);
                    break;
                case "Region_desc":
                    providerOrders = providerOrders.OrderByDescending(key => key.Region.Title);
                    break;
                case "ServiceType":
                    providerOrders = providerOrders.OrderBy(key => key.ServiceType.Title);
                    break;
                case "ServiceType_desc":
                    providerOrders = providerOrders.OrderByDescending(key => key.ServiceType.Title);
                    break;
                case "ClientName":
                    providerOrders = providerOrders.OrderBy(key => key.ClientName);
                    break;
                case "ClientName_desc":
                    providerOrders = providerOrders.OrderByDescending(key => key.ClientName);
                    break;
            }
            var pageSize = 5;
            var pageNumber = (page ?? 1);
            return View(providerOrders.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [Authorize(Roles = "client")]
        public ActionResult GetFreeTime(DateTime date, string providerId)
        {
            try
            {
                return Json(new { freeHours = JsonConvert.SerializeObject(_orderService.GetProviderFreeTime(date, providerId)) }, JsonRequestBehavior.AllowGet); 
            }
            catch (Exception exception)
            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, exception.Message);
            }
        }
    }
}

root/Source/ServiceOrder.WebSite/Views/Shared/MessageView.cshtml
@model ServiceOrder.ViewModel.ViewModels.Implementation.ResultMessageViewModel

@{
    ViewBag.Title = "MessageView";
}

<h2>@Model.Message</h2>

@Html.ActionLink("Back", null, null, null, new { href = Request.UrlReferrer }) |

root/Source/ServiceOrder.WebSite/Views/Shared/NotFound.cshtml
@{
    // 404 Not Found
    //
    // This view was added by NotFoundMVC
    // For inspiration see: https://www.google.be/search?q=example+404+page
    //
    // The following properties are available in the ViewBag:
    // ViewData["RequestedUrl"]
    // ViewData["ReferrerUrl"]
    //

    ViewBag.Title = "Page Not Found";
}
@Styles.Render("~/Content/404css")

@*    <h1>Page Not Found</h1>

    <p>Could not find the page: @ViewBag.RequestedUrl</p>
    @@if (ViewBag.ReferrerUrl != null)
        //{
        //    <p>Go back to the <a href="@ViewBag.ReferrerUrl">previous page</a>.</p>
        //}*@
<div class="wrap">
    <!---start-header---->
    
    <!---End-header---->
    <!--start-content------>
    <div class="content">
        <img src="/Images/error-img.png" title="error" />
        <p><span><label>O</label>hh.....</span>You Requested the page @ViewBag.ReferrerUrl that is no longer There.</p>
        <a href="/Home/Index/">Back To Home</a>
    </div>
    <!--End-Cotent------>
</div>

@* Error page must be longer than 512 bytes for IE and Chrome to show it. So add padding in case we're short. *@
@(new string(' ', 512))

root/Source/ServiceOrder.WebSite/Views/Shared/UserFunctions.cshtml
@if (Request.IsAuthenticated)
{
    if (User.IsInRole("client"))
    {
        <li>@Html.ActionLink("Order service", "Index", "ServiceProviders")</li>
        <li>@Html.ActionLink("My orders","ClientOrders","Order")</li>
    }
    else
    {
        if (User.IsInRole("service provider"))
        {
            <li>@Html.ActionLink("My orders", "ProviderOrders", "Order")</li>
            <li>@Html.ActionLink("Manage", "Manage", "ServiceProviders")</li>
        }
        if (User.IsInRole("admin"))
        {
            <li>@Html.ActionLink("Categories","Index","Category")</li>
            <li>@Html.ActionLink("Regions","Index","Region")</li>
            <li>@Html.ActionLink("Services","Index","ServiceType")</li>
        }
    }

}

root/Source/ServiceOrder.WebSite/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - ServiceOrder</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/less")
    @Styles.Render("~/bundles/kendoCommonCss")
    @Styles.Render("~/bundles/kendoDefaultCss")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/kendo")
    @Scripts.Render("~/bundles/ajax")

</head>
<body>

    <div class="navbar navbar-default navbar-fixed-top nav-bar-color">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Service Order", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @Html.Partial("UserFunctions")
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()

    </div>

<footer class="footer">
    <div class="footer-container">
        <p>&copy;SamSolutions @DateTime.Now.Year - Dmitry ServiceOrder Project</p>
    </div>
</footer>

@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>