root/Source/ServiceOrder.WebSite/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace ServiceOrder.WebSite.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    /*public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }*/

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

root/Source/ServiceOrder.WebSite/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ServiceOrder.Logic.Services;
using ServiceOrder.ViewModel.ViewModels.Implementation;
using ServiceOrder.ViewModel.ViewModels.Implementation.PhotoViewModels;

namespace ServiceOrder.WebSite.Controllers
{
    public class AlbumController : Controller
    {
        private IAlbumService _albumService;

        public AlbumController(IAlbumService albumService)
        {
            _albumService = albumService;
        }

        [Authorize(Roles = "service provider")]
        public ActionResult Add(int albumId)
        {
            var album = _albumService.Get(albumId);
            if (album == null)
            {
                return View("MessageView", new ResultMessageViewModel() {Message = "There's no such album"});
            }
            return User.Identity.GetUserId() != album.ServiceProviderId
                ? View("MessageView", new ResultMessageViewModel() {Message = "You don't has access to this album"})
                : View(album);
        }

        [HttpPost]
        [Authorize(Roles = "service provider")]
        public JsonResult Upload(int albumId)
        {
            var files = new List<AbstractDataUploadResult>();

            _albumService.UploadAndShowResults(HttpContext, files, albumId);

            bool isEmpty = !files.Any();
            return isEmpty ? Json("Error") : Json(new {files = files});
        }

        [Authorize(Roles = "service provider")]
        public ActionResult Edit(int albumId)
        {
            var album = _albumService.Get(albumId);
            if (album == null)
            {
                return View("MessageView", new ResultMessageViewModel() {Message = "There's no such album"});
            }
            return User.Identity.GetUserId() != album.ServiceProviderId
                ? View("MessageView", new ResultMessageViewModel() {Message = "You don't has access to this album"})
                : View(album);
        }

        public JsonResult GetFileList(int albumId)
        {
            try
            {  
                var list = _albumService.GetPhotosList(albumId);
                return Json(new {files = list}, JsonRequestBehavior.AllowGet);
            }
            catch (Exception exception)
            {
                Response.StatusCode = (int) HttpStatusCode.BadRequest;
                Response.StatusDescription = exception.Message;
                return Json(new {success = false}, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [Authorize(Roles = "service provider")]
        public ActionResult ChangeAlbumTitle(int albumId,string albumTitle)
        {
            var result = _albumService.ChangeAlbumTitle(User.Identity.GetUserId(), albumId, albumTitle);
            if (result.Equals(String.Empty))
            {
                return new HttpStatusCodeResult(200, "OK");
            }
            return new HttpStatusCodeResult(400, result);
        }
    }
}

root/Source/ServiceOrder.WebSite/Controllers/OrderController.cs
using System;
using System.Linq;
using System.Net;
using System.Text;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using PagedList;
using ServiceOrder.Logic.Services;
using ServiceOrder.ViewModel.ViewModels.Implementation;
using ServiceOrder.ViewModel.ViewModels.Implementation.Order;
using ServiceOrder.ViewModel.ViewModels.Implementation.ServiceProvidersViewModels;

namespace ServiceOrder.WebSite.Controllers
{
    public class OrderController : Controller
    {
        private IOrderService _orderService;
        private IServiceProviderService _serviceProviderService;
        private ICategoryService _categoryService;

        public OrderController(IOrderService orderService, IServiceProviderService serviceProviderService,
            ICategoryService categoryService)
        {
            _orderService = orderService;
            _serviceProviderService = serviceProviderService;
            _categoryService = categoryService;
        }

        // GET: Order
        [Authorize(Roles = "client")]
        public ActionResult Index(string providerId)
        {
            var provider = new ServiceProviderViewModel();
            try
            {
                provider = _serviceProviderService.Get(providerId);
            }
            catch (Exception exception)
            {
                return View("MessageView", new ResultMessageViewModel {Message = exception.Message});
            }

            if (provider == null)
            {
                return View("MessageView", new ResultMessageViewModel {Message = "There is not such provider"});
            }

            var model = new OrderViewModel();
            foreach (var region in provider.Regions)
            {
                model.Regions.Add(region);
            }

            foreach (var service in provider.Services)
            {
                if (model.Categories.Count(category => category.Id == service.Category.Id) == 0x0)
                {
                    model.Categories.Add(service.Category);
                }
            }

            model.Regions.Sort((firstRegion, secondRegion) => firstRegion.Id.CompareTo(secondRegion.Id));
            model.Categories.Sort((firstCategory, secondCategory) => firstCategory.Id.CompareTo(secondCategory.Id));
            model.ServiceProviderId = provider.Id;
            model.ProviderName = provider.Name;

            return View(model);
        }


        [HttpGet]
        [Authorize(Roles = "client")]
        public ActionResult GetProviderServicesByCategory(int categoryId, string providerId)
        {
            ServiceProviderViewModel provider;
            try
            {
                provider = _serviceProviderService.Get(providerId);
                if (_categoryService.Get(categoryId) == null)
                {
                    throw new Exception("Wrong category");
                }

            }
            catch (Exception exception)
            {

                return new HttpStatusCodeResult(400, exception.Message);
            }

            if (provider.Services.Count(service => service.Category.Id == categoryId) == 0x0)
            {
                return new HttpStatusCodeResult(400, "This provider doesn't has services in this category");
            }
            var shortServices =
                provider.Services.Where(item => item.Category.Id == categoryId)
                    .Select(item => new ServiceShortViewModel {Id = item.Id, Title = item.Title});
            return Json(new {services = JsonConvert.SerializeObject(shortServices)}, JsonRequestBehavior.AllowGet);

        }

        [HttpPost]
        [Authorize(Roles = "client")]
        public ActionResult MakeOrder(OrderViewModel order)
        {
            if (order == null)
            {
                return new HttpStatusCodeResult(400, "Null order");
            }
            try
            {
                order.ClientId = User.Identity.GetUserId();
                _orderService.Add(order);
            }
            catch (AggregateException aggregateException)
            {
                var builder = new StringBuilder();
                foreach (var exception in aggregateException.InnerExceptions)
                {
                    builder.Append(exception.Message);
                }
                return new HttpStatusCodeResult(400, builder.ToString());
            }
            catch (Exception exception)
            {
                return new HttpStatusCodeResult(400, exception.Message);
            }
            return new HttpStatusCodeResult(200, "");
        }

        [HttpGet]
        [Authorize(Roles = "client")]
        public ActionResult ClientOrders(int? page,string sortOrder)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSort = sortOrder == "Date" ? "Date_desc" : "Date";
            ViewBag.RegionSort = sortOrder == "Region" ? "Region_desc" : "Region";
            ViewBag.ServiceTypeSort = sortOrder == "ServiceType" ? "ServiceType_desc" : "ServiceType";
            ViewBag.ProviderNameSort = sortOrder == "ProviderName" ? "ProviderName_desc" : "ProviderName";

            var clientOrders = _orderService.FindClientOrders(User.Identity.GetUserId());
            switch (sortOrder)
            {
                case "Date":
                    clientOrders = clientOrders.OrderBy(key => key.Date);
                    break;
                case "Date_desc":
                    clientOrders = clientOrders.OrderByDescending(key => key.Date);
                    break;
                case "Region":
                    clientOrders = clientOrders.OrderBy(key => key.Region.Title);
                    break;
                case "Region_desc":
                    clientOrders = clientOrders.OrderByDescending(key => key.Region.Title);
                    break;
                case "ServiceType":
                    clientOrders = clientOrders.OrderBy(key => key.ServiceType.Title);
                    break;
                case "ServiceType_desc":
                    clientOrders = clientOrders.OrderByDescending(key => key.ServiceType.Title);
                    break;
                case "ProviderName":
                    clientOrders = clientOrders.OrderBy(key => key.ProviderName);
                    break;
                case "ProviderName_desc":
                    clientOrders = clientOrders.OrderByDescending(key => key.ProviderName);
                    break;
            }
            var pageSize = 5;
            var pageNumber = (page ?? 1);
            return View(clientOrders.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [Authorize(Roles = "service provider")]
        public ActionResult ProviderOrders(int? page, string sortOrder)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.DateSort = sortOrder == "Date" ? "Date_desc" : "Date";
            ViewBag.RegionSort = sortOrder == "Region" ? "Region_desc" : "Region";
            ViewBag.ServiceTypeSort = sortOrder == "ServiceType" ? "ServiceType_desc" : "ServiceType";
            ViewBag.ClientNameSort = sortOrder == "ClientName" ? "ClientName_desc" : "ClientName";

            var providerOrders = _orderService.FindProviderOrders(User.Identity.GetUserId());
            switch (sortOrder)
            {
                case "Date":
                    providerOrders = providerOrders.OrderBy(key => key.Date);
                    break;
                case "Date_desc":
                    providerOrders = providerOrders.OrderByDescending(key => key.Date);
                    break;
                case "Region":
                    providerOrders = providerOrders.OrderBy(key => key.Region.Title);
                    break;
                case "Region_desc":
                    providerOrders = providerOrders.OrderByDescending(key => key.Region.Title);
                    break;
                case "ServiceType":
                    providerOrders = providerOrders.OrderBy(key => key.ServiceType.Title);
                    break;
                case "ServiceType_desc":
                    providerOrders = providerOrders.OrderByDescending(key => key.ServiceType.Title);
                    break;
                case "ClientName":
                    providerOrders = providerOrders.OrderBy(key => key.ClientName);
                    break;
                case "ClientName_desc":
                    providerOrders = providerOrders.OrderByDescending(key => key.ClientName);
                    break;
            }
            var pageSize = 5;
            var pageNumber = (page ?? 1);
            return View(providerOrders.ToPagedList(pageNumber, pageSize));
        }

        [HttpGet]
        [Authorize(Roles = "client")]
        public ActionResult GetFreeTime(DateTime date, string providerId)
        {
            try
            {
                return Json(new { freeHours = JsonConvert.SerializeObject(_orderService.GetProviderFreeTime(date, providerId)) }, JsonRequestBehavior.AllowGet); 
            }
            catch (Exception exception)
            {

                return new HttpStatusCodeResult(HttpStatusCode.BadRequest, exception.Message);
            }
        }
    }
}

root/Source/ServiceOrder.WebSite/Controllers/PhotoController.cs
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using ServiceOrder.Logic.Services;

namespace ServiceOrder.WebSite.Controllers
{
    public class PhotoController : Controller
    {
        private IPhotoService _photoService;
        public PhotoController(IPhotoService photoService)
        {
            _photoService = photoService;
        }
        public FileContentResult Get(int? photoId)
        {
            var photo = _photoService.GetPhoto(photoId);
            if (photo == null) return null;
            return File(photo.PhotoImage,photo.ContentType,photo.FileName);
        }

        [Authorize(Roles = "service provider")]
        [HttpGet]
        public JsonResult Delete(int? photoId)
        {
            _photoService.Delete(photoId,User.Identity.GetUserId());
            return Json("OK", JsonRequestBehavior.AllowGet);
        }
    }
}

root/Source/ServiceOrder.WebSite/Views/ServiceProviders/AddAlbum.cshtml
@model ServiceOrder.ViewModel.ViewModels.Implementation.AlbumViewModels.ShortAlbumViewModel

@{
    ViewBag.Title = "Add Album";
}

<h2>Add Album</h2>


<div class="row">
    @using (Html.BeginForm("AddAlbum", "ServiceProviders", FormMethod.Post, new { @class = "category-create-form col-md-offset-3 col-md-6 col-sm-offset-2 col-sm-8 col-xs-10" }))
    {
    @Html.AntiForgeryToken()

        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", placeholder = "Album Title" } })
        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <input type="submit" value="Create" class="btn btn-default" />

    }
</div>

<div>
    @Html.ActionLink("Back to Managment", "Manage", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

root/Source/ServiceOrder.WebSite/Views/ServiceProviders/Index.cshtml
@model ServiceOrder.ViewModel.ViewModels.Implementation.ServiceProvidersViewModels.ServiceProviderPaginationFiltrationList
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Providers";
}

<h2>Providers of Services</h2>

<span id="notification" style="display: none;"></span>

@using(Html.BeginForm("Filter", "ServiceProviders",FormMethod.Get)){
    <div class="filter-area">
        <div class="row">
            @Html.HiddenFor(model => model.Page)

            <div class="col-md-3 col-xs-6 col-sm-4">
                <input id="filter-region" name="RegionId" value="1" style="width: 90%; min-width: 70px; margin: 10px auto;" />
            </div>
            <div class="col-md-3 col-xs-6 col-sm-4">
                <input id="filter-category" name="CategoryId" value="1" style="width: 90%; min-width: 70px; margin: 10px auto;" />
            </div>
            <div class="col-md-3 col-xs-6 col-sm-4">
                <input id="filter-service" name="ServiceId" value="1" style="width: 90%; min-width: 70px; margin: 10px auto;" />
            </div>
            <div class="col-md-3 col-xs-6 col-sm-4">
                <input type="submit" value="Filter" class="btn btn-default filter-btn" />
            </div>
        </div>

    </div>
}


<table class="table">
    <tr class="table-header-tr table-td-textCenter">
        <th class="col-md-3 col-sm-4 col-xs-4  table-td-textCenter" >
            Provider Name
        </th>
        <th class="col-md-6 col-sm-6 col-xs-6  table-td-textCenter">
            Description
        </th>
        <th class="col-md-2 col-sm-2 col-xs-2 "></th>
    </tr>

    @foreach (var item in Model.ProviderList) {
        <tr >
            <td class="col-md-3 col-sm-4 col-xs-4 serviceProviderIndex-tableTd-vertAligment">
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td class="col-md-6 col-sm-6 col-xs-6">
                @Html.DisplayFor(moderItem => item.ShortDescription)
            </td>
            <td class="col-md-2 col-sm-2 col-xs-2 serviceProviderIndex-tableTd-vertAligment serviceProviderIndex-lastTableTd-center">
                @Html.ActionLink("Make order","Index","Order",new {providerId = item.Id}, new { @class = "btn btn-default" })
            </td>
        </tr>
    }
</table>

<br />
Page @(Model.ProviderList.PageCount < Model.ProviderList.PageNumber ? 0 : Model.ProviderList.PageNumber) of @Model.ProviderList.PageCount

@Html.PagedListPager(Model.ProviderList, page => Url.Action("Filter",new {page, Model.RegionId,Model.CategoryId,Model.ServiceId}))


<script id="errorTemplate" type="text/x-kendo-template">
    <div class="error-notification">
        <img src="http://demos.telerik.com/kendo-ui/content/web/notification/error-icon.png" />
        <h3>#= title #</h3>
        <p>#= message #</p>
    </div>
</script>

<script id="successTemplate" type="text/x-kendo-template">
    <div class="success-notification">
        <img src="http://demos.telerik.com/kendo-ui/content/web/notification/success-icon.png" />
        <h3>#= message #</h3>
    </div>
</script>

<script>
    $(document).ready(function () {

        var modelServiceId =@(Html.Raw(Json.Encode(Model.ServiceId)));
        var modelCategoryId = @(Html.Raw(Json.Encode(Model.CategoryId)));
        var modelRegionId = @(Html.Raw(Json.Encode(Model.RegionId)));

        var notification = $("#notification").kendoNotification({
            position: {
                pinned: true,
                top: 50,
                right: 30
            },
            autoHideAfter: 5000,
            stacking: "down",
            templates: [{
                type: "error",
                template: $("#errorTemplate").html()
            }, {
                type: "success",
                template: $("#successTemplate").html()
            }]
        }).data("kendoNotification");

        var regionDropDownList = $("#filter-region").kendoDropDownList({
            optionLabel: {
                Title: "Select region",
                Id: 0
            },
            dataTextField: "Title",
            dataValueField: "Id"
        }).data("kendoDropDownList");

        var categoryDropDownList = $("#filter-category").kendoDropDownList({
            optionLabel: {
                Title: "Select category",
                Id: 0
            },
            dataTextField: "Title",
            dataValueField: "Id",
            change: onChangeCategory
        }).data("kendoDropDownList");

        var serviceDropDownList = $("#filter-service").kendoDropDownList({
            optionLabel: {
                Title: "Select service type",
                Id:0
            } ,
            dataTextField: "Title",
            dataValueField: "Id"
        }).data("kendoDropDownList");

        serviceDropDownList.enable(false);

        firstLoad();

        function firstLoad() {
            loadAjaxCategory();
            loadAjaxRegion();
        }

        function loadAjaxRegion() {
            $.ajax({
                url: '/ServiceProviders/GetRegions',
                type: 'GET',
                success: function (data) {
                    regionDropDownList.setDataSource([]);
                    var obj = JSON.parse(data.regions);
                    obj.forEach(function (item, i, arr) {
                        regionDropDownList.dataSource.add({ Title: item.Title, Id: item.Id });
                    });
                    if (modelRegionId != null && modelRegionId > 0) {
                        regionDropDownList.select(modelRegionId);
                    } else {
                        regionDropDownList.select(0);
                    }
                    
                },
                error: function (error) {
                    notification.show({
                        title: "Error",
                        message: error.statusText
                    }, "error");
                }
            });
        }

        function loadAjaxCategory() {
            $.ajax({
                url: '/ServiceProviders/GetCategories',
                type: 'GET',
                success: function (data) {
                    categoryDropDownList.setDataSource([]);
                    var obj = JSON.parse(data.categories);
                    obj.forEach(function (item, i, arr) {
                        categoryDropDownList.dataSource.add({ Title: item.Title, Id: item.Id });
                    });
                    if (modelCategoryId != null && modelCategoryId > 0) {
                        categoryDropDownList.select(modelCategoryId);
                        onChangeCategory();
                    } else {
                        categoryDropDownList.select(0);
                    }
                    
                },
                error: function (error) {
                    notification.show({
                        title: "Error",
                        message: error.statusText
                    }, "error");
                }
            });
        }

        function loadAjaxServiceType(category) {
            $.ajax({
                url: '/ServiceProviders/GetCategoryServicesAll',
                type: 'GET',
                data: { Id: category.Id },
                success: function (data) {
                    serviceDropDownList.enable();
                    serviceDropDownList.setDataSource([]);
                    var obj = JSON.parse(data.services);
                    obj.forEach(function (item, i, arr) {
                        serviceDropDownList.dataSource.add({ Title: item.Title, Id: item.Id });
                    });
                    if (modelServiceId != null && modelServiceId > 0) {
                        obj.forEach(function(item, i, arr) {
                            if (item.Id == modelServiceId)
                            {
                                serviceDropDownList.select(i+1);
                            }
                        });
                    } else {
                        serviceDropDownList.select(0);
                    }
                    
                },
                error: function (error) {
                    notification.show({
                        title: "Error",
                        message: error.statusText
                    }, "error");
                }
            });
        }

        function onChangeCategory() {
            var category = categoryDropDownList.dataItem();
            if (category.Id == 0) {
                serviceDropDownList.enable(false);
            } else {
                loadAjaxServiceType(category);
            }

        }
    });

</script>

root/Source/ServiceOrder.WebSite/Views/ServiceProviders/ManageAlbum.cshtml
@model ServiceOrder.ViewModel.ViewModels.Implementation.AlbumViewModels.AlbumViewModel

@{
    ViewBag.Title = "Manage Album";
}

@Styles.Render("~/Content/jQuery-File-Upload")
@Styles.Render("~/Content/Blueimp-Gallery")

<h2>Manage <strong>@Model.Title</strong> Album</h2>

<span id="notification" style="display: none;"></span>

<div class= "albumManage-changeTitleForm row">
    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger " })
        @Html.HiddenFor(model => model.Id)
        <div>
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-lg-2 col-md-2 col-sm-3 col-xs-3 before-input-label" })
            <div class="col-lg-8 col-md-8 col-sm-9 col-xs-9">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control " } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })

            </div>
            <div class="col-xs-2 col-sm-4 visible-sm visible-xs"></div>
            <input type="submit" value="Change Title" class="btn btn-default albumMahage-changeTitleButton col-lg-2 col-md-2 col-sm-3 col-xs-4" />
        </div>

    </div>
</div>               
    

<div class="row">
    <div class="col-xs-1 visible-xs"></div>
    @Html.ActionLink("Add photos", "Add", "Album", new {albumId = Model.Id}, new {@class = "btn btn-success albumButton col-lg-2 col-lg-offset-3 col-md-2 col-md-offset-3  col-sm-3 col-sm-offset-2 col-xs-4"})
    <div class="col-xs-2 visible-xs"></div>
    @Html.ActionLink("Edit photos", "Edit", "Album", new {albumId = Model.Id}, new {@class = "btn btn-warning albumButton col-lg-2 col-lg-offset-1 col-md-2 col-md-offset-1 col-sm-3 col-sm-offset-2 col-xs-4" })

</div>

<div class="col-md-12  col-lg-12 col-sm-12 col-xs-12 galleryMargin">
    <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls" data-filter=":even">
        <div class="slides"></div>
        <h3 class="title"></h3>
        <a class="prev">‹</a>
        <a class="next">›</a>
        <a class="close">×</a>
        <a class="play-pause"></a>
        <ol class="indicator"></ol>
    </div>
    <div id="links">
        @if (@Model.AlbumPhotos != null && @Model.AlbumPhotos.Any())
        {
            foreach (var file in @Model.AlbumPhotos)
            {
            <a href="@Url.Action("Get", "Photo", new { photoId = file.Id })" title="@file.FileName"><img src="@Url.Action("Get", "Photo", new { photoId = file.Id })" alt="@file.FileName" class="imageThumbnailSize"></a>
            }
        }
        else
        {
        <p>No files</p>
        }
        <!--Your files goes here-->
    </div>
</div>

<div class="row">
    @Html.ActionLink("Back to Management", "Manage", "ServiceProviders", null, new { @class = "btn btn-default backButtonMargin" })
</div>

<script id="errorTemplate" type="text/x-kendo-template">
    <div class="error-notification">
        <img src="http://demos.telerik.com/kendo-ui/content/web/notification/error-icon.png" />
        <h3>#= title #</h3>
        <p>#= message #</p>
    </div>
</script>

<script id="successTemplate" type="text/x-kendo-template">
    <div class="success-notification">
        <img src="http://demos.telerik.com/kendo-ui/content/web/notification/success-icon.png" />
        <h3>#= message #</h3>
    </div>
</script>

<script>

    document.getElementById('links').onclick = function (event) {
        event = event || window.event;
        var target = event.target || event.srcElement,
            link = target.src ? target.parentNode : target,
            options = { index: link, event: event },
            links = this.getElementsByTagName('a');
        blueimp.Gallery(links, options);
    };

    var titleInput = $("#Title");
    var lastTitleInputValue = titleInput.val();
    var h2TitleValue = $("h2 strong");

    var notification = $("#notification").kendoNotification({
        position: {
            pinned: true,
            top: 50,
            right: 30
        },
        autoHideAfter: 5000,
        stacking: "down",
        templates: [{
            type: "error",
            template: $("#errorTemplate").html()
        }, {
            type: "success",
            template: $("#successTemplate").html()
        }]
    }).data("kendoNotification");

    $('input:submit').click(function (event) {
        event.preventDefault();

        $.ajax({
            url: '/Album/ChangeAlbumTitle',
            type: 'POST',
            data: {
                albumId: @Model.Id,
                albumTitle: titleInput.val()
            },
            success: function () {
                notification.show({
                    message: "Success Changing"
                }, "success");
                lastTitleInputValue = titleInput.val();
                h2TitleValue.text(lastTitleInputValue);
            },
            error: function (error) {
                notification.show({
                    title: "Error ",
                    message: error.statusText
                }, "error");
                titleInput.val(lastTitleInputValue);
            }
        });
    });
</script>
@Scripts.Render("~/bundles/Blueimp-Gallerry2")